basePath: /
definitions:
  controllers.HTTPError:
    type: object
  controllers.InputMessage:
    properties:
      messageContent:
        type: string
      userID:
        type: string
    type: object
  controllers.Intent:
    properties:
      intentName:
        type: string
      prompt:
        items:
          $ref: '#/definitions/models.Prompt'
        type: array
      reply:
        $ref: '#/definitions/models.ResponseMessage'
      trainingPhrases:
        items:
          type: string
        type: array
    type: object
  controllers.ResponseMessage:
    properties:
      messageContent:
        type: string
      userID:
        type: string
    type: object
  models.Prompt:
    properties:
      paramName:
        type: string
      paramType:
        type: string
      promptQuestion:
        type: string
    type: object
  models.ResponseMessage:
    properties:
      messageContent:
        type: string
      userID:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Chatbot API with Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Chatbot API
  version: "1.0"
paths:
  /ReplyIntent:
    post:
      consumes:
      - application/json
      description: Reply to an intent that is POST request from user
      parameters:
      - description: user id
        in: body
        name: inputMessage
        required: true
        schema:
          $ref: '#/definitions/controllers.InputMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Reply to an intent
  /addIntent:
    post:
      consumes:
      - application/json
      description: Add an intent to DB
      parameters:
      - description: Name of new intent
        in: body
        name: newIntent
        required: true
        schema:
          $ref: '#/definitions/controllers.Intent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Add an intent to DB
  /deleteIntent:
    delete:
      consumes:
      - application/json
      description: Delete an intent from DB, ===ONLY NEED  TO PASS IN IntentName===
      parameters:
      - description: Name of the intent that you want to delete from db
        in: body
        name: intentName
        required: true
        schema:
          $ref: '#/definitions/controllers.Intent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Delte an intent by querying intent name
swagger: "2.0"
