basePath: /
definitions:
  controllers.HTTPError:
    type: object
  controllers.InputMessage:
    properties:
      messageContent:
        type: string
      userID:
        type: string
    type: object
  controllers.Intent:
    properties:
      IntentName:
        type: string
      NewName:
        type: string
      prompts:
        $ref: '#/definitions/models.Prompt'
      reply:
        $ref: '#/definitions/models.ResponseMessage'
      trainingPhrases:
        items:
          type: string
        type: array
    type: object
  controllers.ResponseMessage:
    properties:
      message_content:
        type: string
      user_id:
        type: string
    type: object
  models.Prompt:
    properties:
      promptQuestion:
        items:
          type: string
        type: array
    type: object
  models.ResponseMessage:
    properties:
      message_content:
        type: string
      user_id:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Chatbot API with Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Chatbot API
  version: "1.0"
paths:
  /ReplyIntent:
    post:
      consumes:
      - application/json
      description: Reply to an intent that is POST request from user
      parameters:
      - description: user id
        in: body
        name: inputMessage
        required: true
        schema:
          $ref: '#/definitions/controllers.InputMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Reply to an intent
  /addIntent:
    post:
      consumes:
      - application/json
      description: Add an intent to DB
      parameters:
      - description: Name of new intent
        in: body
        name: newIntent
        required: true
        schema:
          $ref: '#/definitions/controllers.Intent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Add an intent to DB
  /deleteIntent:
    delete:
      consumes:
      - application/json
      description: Delete an intent from DB, ===ONLY NEED  TO PASS IN IntentName===
      parameters:
      - description: Name of the intent that you want to delete from db
        in: body
        name: intentName
        required: true
        schema:
          $ref: '#/definitions/controllers.Intent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Delte an intent by querying intent name
  /listIntent:
    get:
      description: List all intents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Intent'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: List all intents and training phrases
  /modifyIntent:
    patch:
      consumes:
      - application/json
      description: Modify an intent to the body's intent by querying "IntentName".
      parameters:
      - description: The new intent, pass in NewName to change the current name
        in: body
        name: intent
        required: true
        schema:
          $ref: '#/definitions/controllers.Intent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Intent'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Modify an intent
swagger: "2.0"
